### ISSUE TITLE
Reached the limit of file size uploaded on vissE

### ISSUE THREAD

**Issue by sean8802** [ahmohamed/vissEServerRpkg#2]
Hi, I'm Sean Chung from National Taiwan University. I came across this issue when using vissE cloud. When I was uploading my counts matrix file for single cell GSEA analysis, it said the max file size is limited to 200 MB. However, our compressed file was over 499 MB. I was wondering if there's any alternative that allows us to analyse our data by vissE. 
<img width="861" alt="截圖 2023-07-22 下午4 05 26" src="https://github.com/ahmohamed/vissEServerRpkg/assets/109936333/da7143c2-ac60-48c0-bfeb-f20d2eca281c">
There's another problem that our feature matrix consists of six columns. However, the platform notified us only a three-column file is allowed. I wonder which three column should I reserve for the analysis. I'm looking forward for your instruction and thank you for building such a useful platform for GSEA analysis!
<img width="506" alt="截圖 2023-07-22 下午4 11 28" src="https://github.com/ahmohamed/vissEServerRpkg/assets/109936333/050533df-5753-4032-847f-9eae767999ff">

**Comment by bhuvad** [comment]
Hi Sean,

Glad to hear you are finding vissE.cloud useful. To aid you with this matter, we have increased the upload limit and you should be able to upload your files. This may be a temporary increment subject to resource availability (as you are aware vissE.cloud is free to use). We have rarely come across files of such size, and I was curious to know how many cells you had in your experiment and whether they all came from a single sample/batch or across multiple samples/batches. If the latter, please be aware that vissE.cloud does not integrate cells across different batches yet and you may not be able to get sensible results as is. Knowing the number of cells in your assay will really help us gauge the appropriate file size limits and improve the webapp so we appreciate it if you can assist us with this information.

Regarding your second query, the feature table vissE.cloud expects is the standard output from CellRanger. The three columns in this are the first three columns in your table (Ensembl ID, gene symbol, gene type). Discarding the last three columns should fix the issue. Hope this helps you get things running.

Cheers,
Dharmesh

**Comment by sean8802** [comment]
Hi Dharmesh,

I really appreciate your help. Following your instruction, I successfully uploaded our data to the platform. However, vissE reported that more than 90% of genes in our data were not mapped. I tried to expand the geneset collection in the parameter to the extend of all collection but it turned out useless. I wonder what might be wrong with our data. And about the file size, our data came from a single batch and the cell number is about 10000. I hope the information helps. Again, thank you for your support!

<img width="936" alt="截圖 2023-07-25 下午12 05 34" src="https://github.com/ahmohamed/vissEServerRpkg/assets/109936333/ef141c02-4ca7-468f-b288-9c9badb1aa6d">

<img width="803" alt="截圖 2023-07-25 下午12 26 15" src="https://github.com/ahmohamed/vissEServerRpkg/assets/109936333/35b4efc3-a2f2-4123-bf55-c5dba3a3f03c">

Best regards,
Sean

**Comment by bhuvad** [comment]
Hi Sean,

I suspect something is odd with your data. I do not understand why you have 300,000 genes in your data. Did you use a genome that has many unlocalised or unplaced scaffolds? These kinds of reference genomes would have many features that may not be of interest in standard scRNA-seq workflows (thus resulting in the over 300,000 genes). Of those genes, vissE sees that ~20,000 are mapped and these would likely be the protein coding genes. This should be the relevant information.

The reason the job crashes is because it sees many unmapped genes (proportion wise) even though most of the protein coding genes mapped well. This is also the reason why your file sizes are huge. You could use a simpler ensembl genome as the reference genome that focuses on placed scaffolds. If you used CellRanger to produce your counts, you could use the prebuilt human reference genome (https://cf.10xgenomics.com/supp/cell-exp/refdata-gex-GRCh38-2020-A.tar.gz). If you used another software, you should use the primary assembly (https://ftp.ensembl.org/pub/release-110/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz) to generate an index to use for alignment.

Once the data is smaller and the number of genes is ~30,000 (using the primary assembly as a reference), you should be able to run vissE.cloud without any issues.

Cheers,
Dharmesh
